### ISSUE TITLE
T5.2 - Worker profiler

### ISSUE THREAD

**Issue by kostasgrevenitis** [c0c0n3/kitt4sme.live#115]
### Summary
_Task 5.2 – Human competence and capabilities profiling [Leader: GATE, Duration: M11 – M22]_

_This task develops the KITT4SME Worker Profiler, a tool that allows performing a skills gap assessment for the single
worker to be used as an input of the Competence Matchmaking Tool (T5.5) that finds the optimal training plan to fill
those gaps. Three steps are foreseen to develop the Worker Profiler._

_First, inputs from T5.1 are used to identify both the new archetypes requested by the on-going digital transformation and the updated skills to be integrated in the existing archetypes to update them according to the new technological requirements. Second, a map of the skills mismatching is created with a questionnaire._

_The questionnaire will be generated automatically using an AI based approach applied
on the information extracted in the previous point. The tool (offered by GATE) will be used in order to make the
questionnaire design phase more efficient and replicable. Finally, reference standards like ESCO and O*NET are used
to quantify gaps and to create a proper assessment procedure to be integrated into the tool._

### Intended outcome
The worker profiler is a tool able to assess the skill gap of a worker in relation to:
- The technological skill needs driven by AI revolution and what International competence databases define as standards for her/his professional role (should do & want to do);
- The ambitions of the worker (wish to be);
- The technological skill needs driven by the acquisition of a specific AI component in KITT4SME platform.

### How will it work?

In this phase the user can choose the macro job field and subsequently the job field. This information will be fundamental when generating a new questionnaire based on the archetype chosen by the user. 

The generated questionnaire is divided into three main sections (Task, Tools, Soft skills)

#### Task & Tools

The first two parts are related to Tools and Tasks, the user is asked to select the ones that he is familiar with. The selection is proposed via checkbox. All the tools and tasks suggested by the system are extrapolated from the database using the archetype chosen by the user at generation phase as a guide.

#### Soft Skills

The third and final section of the questionnaire will ask the user to select the level of proficiency on soft skills, where 1 is acknowledged as the lowest value and 5 the highest. 

#### Output

This section focuses on the comparison between the answers provided by the user via the assessment and the reference archetype chosen in the questionnaire generation phase. 

#### Three most similar archetypes

The system takes the answers provided by the user and calculates a “similarity score” for every archetype. Finally, the three archetypes with the highest score are selected to be presented as suggestions to the user. This section will be presented in a similar way to the first contrast analysis; the main difference being that the comparison is done between the answer provided by the user and the archetype suggestion selected. Once again, Tools and Tasks that the user needs to acquire for this particular archetype are presented. For what concerns soft skills, they will be presented in a simple table containing for each row the name of the soft skill, the answer provided and an evaluation of the latter. If the answer provided satisfies the requirements in terms of soft skill of that particular archetype, a green check will be visualized, otherwise a red x.  If the worker is interested to measure the skill gap between what he/she currently does and what he/she ideally wants to become, we give the opportunity to select any archetype from the entire list of archetypes. The outputs are the same, except for the three most similar archetypes that will be not included in this case. Tools, task and soft skills extract through the contrast analysis represent the WISH TO BE gap.

![Profilers](https://user-images.githubusercontent.com/2041951/154861888-c83fc9ce-9c1e-44d6-b6df-1039dbe786f4.png)

### Actions

- [x] Design the database
- [x] Improve the backend
- [x] Improve the UI
- [x] Improve business logic
- [ ] Dockerise app (#121)
- [ ] Deploy app (#122)

[examples]: https://github.com/github/roadmap/issues
https://github.com/c0c0n3/kitt4sme/blob/master/arch/catalogue/workpro.md
