### ISSUE TITLE
[Tracking] Data sheets

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#49]
This is a "meta issue" to group and track progress of data sheets.

- [ ] RAMP API for accessing data sheets (query)
- [ ] Finalise data sheet tool WebUI
- [ ] karikolehmainen/kitt4sme-digitaldatasheets#1
- [ ] Retrieve data sheets from RAMP for editing
- [ ] Integrate data sheet tool into RAMP marketplace
- [ ] ...

**Comment by karikolehmainen** [comment]
Other detailed issues related to the digital datasheets:
https://github.com/karikolehmainen/kitt4sme-digitaldatasheets/issues/2#issue-1101660678
https://github.com/karikolehmainen/kitt4sme-digitaldatasheets/issues/3#issue-1101662888
https://github.com/karikolehmainen/kitt4sme-digitaldatasheets/issues/4#issue-1101664262
https://github.com/karikolehmainen/kitt4sme-digitaldatasheets/issues/5#issue-1101665041

**Comment by c0c0n3** [comment]
@karikolehmainen I've updated the task list w/ the issues you linked above. if you could please do any clean up still needed on this task list---I've added you as a collaborator so you should be able to edit the issue I think...
