### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#5]
Use local storage for the cluster data. VTT VM's got about 35GB. Is it gona be enough? Can up if needed.

- [x] enable MicroK8s local storage (see [this][docs.storage])
- [x] create & configure volume for CrateDB (#85)
- [x]   create & configure volume for Keycloak (#68)
- [x] create & configure volume for MongoDB (#173)

[docs.storage]: https://github.com/c0c0n3/kitt4sme.live/blob/crate/docs/storage.md
