### ISSUE TITLE
[Tracking] Security

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#53]
This is a "meta issue" to group and track progress of platform security.

* [ ] RAMP migration to Keycloak; should Keycloak be in KITT4SME? see #9.
* [ ] Single sign-on b/w KITT4SME & RAMP
* [ ] Multi-tenancy policies: port OIDC+OPA from initial proto, see #8 and #11.
* [ ] #29
* [ ] #30 
* [ ] #40
* [ ] #52
* [ ] ...
