### ISSUE TITLE
[Tracking] Architecture updates

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#58]
This is a "meta issue" to group and track progress of updates to the architecture docs.

- [ ] update functional decomposition
- [ ] update security + examples from initial proto
- [ ] scenarios---content to come from code developed for pilot deployments
