### ISSUE TITLE
[Tracking] Tutorials & templates

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#64]
This is a "meta issue" to group and track progress of tutorials & templates.

- [ ] Deploying a simple AI service---lift code and docs from [Roughnator][roughnator].
- [ ] Developing a simple AI service---lift code and docs from [Roughnator][roughnator].
- [ ] Platform routing
- [ ] Platform monitoring
- [ ] Platform mesh deployment---see also #60
- [x] Platform bootstrap

[roughnator]: https://github.com/c0c0n3/kitt4sme.roughnator
