### ISSUE TITLE
2021 Report: Assets

### ISSUE THREAD

**Issue by c0c0n3** [c0c0n3/kitt4sme.live#86]
We've got to add a chapter to the 2021 Periodic Report where we detail what software each partner brings to the project and its role in the architecture.

Each partner should contribute the following content---max one page.

- **High-level functionality**. Short description of the software and its purpose in KITT4SME---focus on functionality, not the technical wiring within the platform. Don't copy-paste from the DoA.
- **Role in the architecture**. Where does this component fit in the KITT4SME architecture? (E.g. platform app service.) How does it integrate in the architecture? (E.g. through pub/sub.) Add a diagram to guide the reader if possible.
- **Requirements**. Map KITT4SME requirements to functionality provided by this component---focus on how this is going to help SMEs make the most out of the platform. Reference the user journey if possible.
- **Improvements**. What improvements have been made to make the software fulfill its role in the platform? What resources have been used?
- **Value proposition**. Why is this development valuable within KITT4SME? Focus on how the component helps the platform reach its stated objectives and goals.
- **Deployment**. How's the component deployed? Is it a cloud service or an on-prem component? How to secure communication?

**Comment by c0c0n3** [comment]
* Powered by FIWARE Middleware for AI (MAR)
* Digital Datasheets for Modules Composability (VTT)
* SMEs-Oriented Platform Configurator (SUPSI)
* RAMP Marketplace (VTT, ED)
* Worker Profiler (HOL, GATE)
* Production System Profiler (HOL, WUT)
* Catalogue of Qualified Training Experiences (GATE)
* Competence Matchmaking Tool (GATE)
* AI for Quality Inspection Systems (R2M)
* Fatigue Monitoring System (SUPSI)
* Vision for Quality Excellence (ROVI)
* Shop Floor Anomalies Detection System (GINKGO)
* Intervention Manager (SUPSI)
* Manufacturing Process Management System (ED, CSIC)
* Shop Floor Reconfigurator (CSIC)
* AI-Learn (GATE?)
* Techimetro? (GATE)
* Sensing Layer (HOL)
* Quantum Leap (MAR)
* Adaptive Questionnaire (SUPSI)
* Quality Control in manufacturing operations in the Pilot Line GAMHE 5.0: Micro-mechanical milling (CSIC)

**Comment by kostasgrevenitis** [comment]
We need to define a integration testing pipeline. Ideas from here:

1. https://medium.com/swlh/the-ultimate-guide-to-integration-testing-with-docker-compose-and-sql-f288f05032c9
2. https://blog.harrison.dev/2016/06/19/integration-testing-with-docker-compose.html

**Comment by c0c0n3** [comment]
Contribs received so far:

- [x] Shop Floor Anomalies Detection System (Ginkgo, #93)
- [x] AI for Quality Inspection Systems (R2M, email; @rx2dev can the content be made public?)
- [x] Vision for Quality Excellence (Rovimatica, email; @innovacion-rovi can the content be made public?)
- [x] Worker Profiler (Holonix, #92)
- [x] "Powered by FIWARE" Middleware for AI (Martel, #94)
- [x] QuantumLeap (Martel, #94)

**Comment by innovacion-rovi** [comment]
we have no problem to make it public

**Comment by c0c0n3** [comment]
content handed over to SUPSI, they'll drive the editing of the document to be sent to EC reviewers.
